/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csysorg.gui;

import java.awt.Image;
import java.io.InputStream;
import java.io.OutputStream;
import javax.microedition.io.Connector;
import javax.microedition.io.StreamConnection;
import javax.swing.ImageIcon;

/**
 *
 * @author NeilOliver
 */
import javax.swing.JLabel;

public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        connectionLabel = new javax.swing.JLabel();
        LED2 = new javax.swing.JLabel();
        LED1 = new javax.swing.JLabel();
        LED3 = new javax.swing.JLabel();
        LED4 = new javax.swing.JLabel();
        LED5 = new javax.swing.JLabel();
        LED6 = new javax.swing.JLabel();
        LED7 = new javax.swing.JLabel();
        LED8 = new javax.swing.JLabel();
        LED9 = new javax.swing.JLabel();
        LED10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSlider14 = new javax.swing.JSlider(0,100);
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButton1.setText("OFF");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Power:");

        jLabel2.setFont(new java.awt.Font("HelveticaNeueLT Std Med", 1, 14)); // NOI18N
        jLabel2.setText("OVERRIDE CONTROLS");

        jLabel3.setText("Status:");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        connectionLabel.setText("Not Connected");

        imageIcon2 = new javax.swing.ImageIcon(getClass().getResource("led-off.png"));
        image2 = imageIcon2.getImage(); // transform it
        newimg2 = image2.getScaledInstance(50, 50,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon2 = new ImageIcon(newimg2);  // transform it back
        LED2.setIcon(imageIcon2);
        LED2.setText("   LED2");
        LED2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LED2MousePressed(evt);
            }
        });

        imageIcon = new javax.swing.ImageIcon(getClass().getResource("led-off.png"));
        image = imageIcon.getImage(); // transform it
        newimg = image.getScaledInstance(50, 50,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon = new ImageIcon(newimg);  // transform it back
        LED1.setIcon(imageIcon);
        LED1.setText("   LED1");
        LED1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LED1MousePressed(evt);
            }
        });

        imageIcon = new javax.swing.ImageIcon(getClass().getResource("led-off.png"));
        image = imageIcon.getImage(); // transform it
        newimg = image.getScaledInstance(50, 50,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon = new ImageIcon(newimg);  // transform it back
        LED3.setIcon(imageIcon);
        LED3.setText("   LED3");
        LED3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LED3MousePressed(evt);
            }
        });

        imageIcon = new javax.swing.ImageIcon(getClass().getResource("led-off.png"));
        image = imageIcon.getImage(); // transform it
        newimg = image.getScaledInstance(50, 50,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon = new ImageIcon(newimg);  // transform it back
        LED4.setIcon(imageIcon);
        LED4.setText("   LED4");
        LED4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LED4MousePressed(evt);
            }
        });

        imageIcon = new javax.swing.ImageIcon(getClass().getResource("led-off.png"));
        image = imageIcon.getImage(); // transform it
        newimg = image.getScaledInstance(50, 50,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon = new ImageIcon(newimg);  // transform it back
        LED5.setIcon(imageIcon);
        LED5.setText("   LED5");
        LED5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LED5MousePressed(evt);
            }
        });

        imageIcon = new javax.swing.ImageIcon(getClass().getResource("led-off.png"));
        image = imageIcon.getImage(); // transform it
        newimg = image.getScaledInstance(50, 50,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon = new ImageIcon(newimg);  // transform it back
        LED6.setIcon(imageIcon);
        LED6.setText("   LED6");
        LED6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LED6MousePressed(evt);
            }
        });

        imageIcon = new javax.swing.ImageIcon(getClass().getResource("led-off.png"));
        image = imageIcon.getImage(); // transform it
        newimg = image.getScaledInstance(50, 50,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon = new ImageIcon(newimg);  // transform it back
        LED7.setIcon(imageIcon);
        LED7.setText("   LED7");
        LED7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LED7MousePressed(evt);
            }
        });

        imageIcon = new javax.swing.ImageIcon(getClass().getResource("led-off.png"));
        image = imageIcon.getImage(); // transform it
        newimg = image.getScaledInstance(50, 50,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon = new ImageIcon(newimg);  // transform it back
        LED8.setIcon(imageIcon);
        LED8.setText("   LED8");
        LED8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LED8MousePressed(evt);
            }
        });

        imageIcon = new javax.swing.ImageIcon(getClass().getResource("led-off.png"));
        image = imageIcon.getImage(); // transform it
        newimg = image.getScaledInstance(50, 50,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon = new ImageIcon(newimg);  // transform it back
        LED9.setIcon(imageIcon);
        LED9.setText("   LED9");
        LED9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LED9MousePressed(evt);
            }
        });

        imageIcon = new javax.swing.ImageIcon(getClass().getResource("led-off.png"));
        image = imageIcon.getImage(); // transform it
        newimg = image.getScaledInstance(50, 50,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon = new ImageIcon(newimg);  // transform it back
        LED10.setIcon(imageIcon);
        LED10.setText("   LED10");
        LED10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LED10MousePressed(evt);
            }
        });

        jLabel5.setText("Light Intensity");

        jSlider14.setMajorTickSpacing(10);
        jSlider14.setMinorTickSpacing(1);
        jSlider14.setPaintTicks(true);
        jSlider14.setPaintLabels(true);

        jButton2.setText("Connect");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LED2)
                    .addComponent(LED1)
                    .addComponent(LED3)
                    .addComponent(LED4)
                    .addComponent(LED5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LED10)
                        .addGap(349, 349, 349))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LED6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LED7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LED8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LED9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSlider14, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(connectionLabel)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(194, 194, 194))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(connectionLabel)
                    .addComponent(jButton2))
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jSlider14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LED1)
                            .addComponent(LED6))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LED2)
                            .addComponent(LED7))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LED3)
                            .addComponent(LED8))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LED4)
                            .addComponent(LED9))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LED5)
                            .addComponent(LED10))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (jToggleButton1.getText() == "OFF") {
            jToggleButton1.setText("ON");
        } else if (jToggleButton1.getText() == "ON") {
            turnOff();
            jToggleButton1.setText("OFF");
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void LED1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LED1MousePressed
        LED1State = LEDPressed(LED1, LED1State);
        if (LED1State == true) {
            OSWrite("");
            System.out.println("");
        } else {
            OSWrite("");
            System.out.println("");
        }

    }//GEN-LAST:event_LED1MousePressed

    private void LED2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LED2MousePressed
        LED2State = LEDPressed(LED2, LED2State);
        if (LED2State == true) {
            OSWrite("");
            System.out.println("");
        } else {
            OSWrite("");
            System.out.println("");
        }
    }//GEN-LAST:event_LED2MousePressed

    private void LED3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LED3MousePressed
        LED3State = LEDPressed(LED3, LED3State);
        if (LED3State == true) {
            OSWrite("");
            System.out.println("");
        } else {
            OSWrite("");
            System.out.println("");
        }
    }//GEN-LAST:event_LED3MousePressed

    private void LED4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LED4MousePressed
        LED4State = LEDPressed(LED4, LED4State);
        if (LED4State == true) {
            OSWrite("");
            System.out.println("");
        } else {
            OSWrite("");
            System.out.println("");
        }
    }//GEN-LAST:event_LED4MousePressed

    private void LED5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LED5MousePressed
        LED5State = LEDPressed(LED5, LED5State);
        if (LED5State == true) {
            OSWrite("");
            System.out.println("");
        } else {
            OSWrite("");
            System.out.println("");
        }
    }//GEN-LAST:event_LED5MousePressed

    private void LED6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LED6MousePressed
        LED6State = LEDPressed(LED6, LED6State);
        if (LED6State == true) {
            OSWrite("");
            System.out.println("");
        } else {
            OSWrite("");
            System.out.println("");
        }
    }//GEN-LAST:event_LED6MousePressed

    private void LED7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LED7MousePressed
        LED7State = LEDPressed(LED7, LED7State);
        if (LED7State == true) {
            OSWrite("");
            System.out.println("");
        } else {
            OSWrite("");
            System.out.println("");
        }
    }//GEN-LAST:event_LED7MousePressed

    private void LED8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LED8MousePressed
        LED8State = LEDPressed(LED8, LED8State);
        if (LED8State == true) {
            OSWrite("");
            System.out.println("");
        } else {
            OSWrite("");
            System.out.println("");
        }
    }//GEN-LAST:event_LED8MousePressed

    private void LED9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LED9MousePressed
        LED9State = LEDPressed(LED9, LED9State);
        if (LED9State == true) {
            OSWrite("");
            System.out.println("");
        } else {
            OSWrite("");
            System.out.println("");
        }
    }//GEN-LAST:event_LED9MousePressed

    private void LED10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LED10MousePressed
        LED10State = LEDPressed(LED10, LED10State);
        if (LED10State == true) {
            OSWrite("");
            System.out.println("");
        } else {
            OSWrite("");
            System.out.println("");
        }
    }//GEN-LAST:event_LED10MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!isConnected) {
            try {
                streamConnection = (StreamConnection) Connector.open(hc05Url);
                os = streamConnection.openOutputStream();
                is = streamConnection.openInputStream();
                connectionLabel.setText("Connected");
                isConnected = true;
                jButton2.setText("Disconnect");
            } catch (Exception ex) {
                ex.printStackTrace();
                connectionLabel.setText("Not Connected");
                jButton2.setText("Reconnect");
            }
        } else if (isConnected) {
            try {
                os.close();
                is.close();
                streamConnection.close();
                jButton2.setText("Connect");
                connectionLabel.setText("Not Connected");
                isConnected = false;
            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void OSWrite(String string) {
        if (isConnected) {
            try {
                os.write(string.getBytes());

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }

    private boolean LEDPressed(JLabel label, boolean LEDstate) {
        if (this.isOn()) {
            if (LEDstate == false) {
                ImageIcon imageIcon = new javax.swing.ImageIcon(getClass().getResource("led-on.png"));
                Image image = imageIcon.getImage();
                Image newimg = image.getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH);
                imageIcon = new ImageIcon(newimg);
                label.setIcon(imageIcon);
                return true;
            } else {
                ImageIcon imageIcon = new javax.swing.ImageIcon(getClass().getResource("led-off.png"));
                Image image = imageIcon.getImage();
                Image newimg = image.getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH);
                imageIcon = new ImageIcon(newimg);
                label.setIcon(imageIcon);
                return false;
            }
        } else {
            return false;
        }
    }

    private boolean isOn() {
        if (jToggleButton1.getText() == "ON") {
            return true;
        } else {
            return false;
        }
    }

    private void turnOff() {
        LED1State = LEDPressed(LED1, true);
        LED2State = LEDPressed(LED2, true);
        LED3State = LEDPressed(LED3, true);
        LED4State = LEDPressed(LED4, true);
        LED5State = LEDPressed(LED5, true);
        LED6State = LEDPressed(LED6, true);
        LED7State = LEDPressed(LED7, true);
        LED8State = LEDPressed(LED8, true);
        LED9State = LEDPressed(LED9, true);
        LED10State = LEDPressed(LED10, true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });

    }

    boolean isConnected = false;
    String hc05Url = "98D331F59D0E";
    StreamConnection streamConnection = null;
    OutputStream os = null;
    InputStream is = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LED1;
    private ImageIcon imageIcon;
    private Image image;
    private Image newimg;
    private boolean LED1State = false;
    private javax.swing.JLabel LED10;
    private boolean LED10State = false;
    private javax.swing.JLabel LED2;
    private ImageIcon imageIcon2;
    private Image image2;
    private Image newimg2;
    private boolean LED2State = false;
    private javax.swing.JLabel LED3;
    private boolean LED3State = false;
    private javax.swing.JLabel LED4;
    private boolean LED4State = false;
    private javax.swing.JLabel LED5;
    private boolean LED5State = false;
    private javax.swing.JLabel LED6;
    private boolean LED6State = false;
    private javax.swing.JLabel LED7;
    private boolean LED7State = false;
    private javax.swing.JLabel LED8;
    private boolean LED8State = false;
    private javax.swing.JLabel LED9;
    private boolean LED9State = false;
    private javax.swing.JLabel connectionLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider14;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

}
